apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restricted-role
  namespace: myapp
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployment", "pods" ]
  verbs: ["get", "watch", "deploy", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-roleBinding
  namespace: myapp
subjects:
- kind: ServiceAccount
  name: restricted-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: restricted-role
  apiGroup: rbac.authorization.k8s.io
